// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: proto/geo_ingest.proto

package geopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoIngestService_SendSingleLocation_FullMethodName = "/geoengine.v1.GeoIngestService/SendSingleLocation"
	GeoIngestService_SendBatchLocation_FullMethodName  = "/geoengine.v1.GeoIngestService/SendBatchLocation"
)

// GeoIngestServiceClient is the client API for GeoIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoIngestServiceClient interface {
	SendSingleLocation(ctx context.Context, in *LocationPing, opts ...grpc.CallOption) (*IngestResponse, error)
	SendBatchLocation(ctx context.Context, in *LocationBatchRequest, opts ...grpc.CallOption) (*IngestResponse, error)
}

type geoIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoIngestServiceClient(cc grpc.ClientConnInterface) GeoIngestServiceClient {
	return &geoIngestServiceClient{cc}
}

func (c *geoIngestServiceClient) SendSingleLocation(ctx context.Context, in *LocationPing, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, GeoIngestService_SendSingleLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoIngestServiceClient) SendBatchLocation(ctx context.Context, in *LocationBatchRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, GeoIngestService_SendBatchLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoIngestServiceServer is the server API for GeoIngestService service.
// All implementations must embed UnimplementedGeoIngestServiceServer
// for forward compatibility.
type GeoIngestServiceServer interface {
	SendSingleLocation(context.Context, *LocationPing) (*IngestResponse, error)
	SendBatchLocation(context.Context, *LocationBatchRequest) (*IngestResponse, error)
	mustEmbedUnimplementedGeoIngestServiceServer()
}

// UnimplementedGeoIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoIngestServiceServer struct{}

func (UnimplementedGeoIngestServiceServer) SendSingleLocation(context.Context, *LocationPing) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSingleLocation not implemented")
}
func (UnimplementedGeoIngestServiceServer) SendBatchLocation(context.Context, *LocationBatchRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBatchLocation not implemented")
}
func (UnimplementedGeoIngestServiceServer) mustEmbedUnimplementedGeoIngestServiceServer() {}
func (UnimplementedGeoIngestServiceServer) testEmbeddedByValue()                          {}

// UnsafeGeoIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoIngestServiceServer will
// result in compilation errors.
type UnsafeGeoIngestServiceServer interface {
	mustEmbedUnimplementedGeoIngestServiceServer()
}

func RegisterGeoIngestServiceServer(s grpc.ServiceRegistrar, srv GeoIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedGeoIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoIngestService_ServiceDesc, srv)
}

func _GeoIngestService_SendSingleLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIngestServiceServer).SendSingleLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIngestService_SendSingleLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIngestServiceServer).SendSingleLocation(ctx, req.(*LocationPing))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoIngestService_SendBatchLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIngestServiceServer).SendBatchLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIngestService_SendBatchLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIngestServiceServer).SendBatchLocation(ctx, req.(*LocationBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoIngestService_ServiceDesc is the grpc.ServiceDesc for GeoIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geoengine.v1.GeoIngestService",
	HandlerType: (*GeoIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSingleLocation",
			Handler:    _GeoIngestService_SendSingleLocation_Handler,
		},
		{
			MethodName: "SendBatchLocation",
			Handler:    _GeoIngestService_SendBatchLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/geo_ingest.proto",
}
