// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/geo_ingest.proto

package geopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsMocked      bool                   `protobuf:"varint,8,opt,name=is_mocked,json=isMocked,proto3" json:"is_mocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationPing) Reset() {
	*x = LocationPing{}
	mi := &file_proto_geo_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationPing) ProtoMessage() {}

func (x *LocationPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationPing.ProtoReflect.Descriptor instead.
func (*LocationPing) Descriptor() ([]byte, []int) {
	return file_proto_geo_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LocationPing) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LocationPing) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationPing) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationPing) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationPing) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationPing) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *LocationPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LocationPing) GetIsMocked() bool {
	if x != nil {
		return x.IsMocked
	}
	return false
}

type LocationBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pings         []*LocationPing        `protobuf:"bytes,1,rep,name=pings,proto3" json:"pings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationBatchRequest) Reset() {
	*x = LocationBatchRequest{}
	mi := &file_proto_geo_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationBatchRequest) ProtoMessage() {}

func (x *LocationBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationBatchRequest.ProtoReflect.Descriptor instead.
func (*LocationBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_geo_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *LocationBatchRequest) GetPings() []*LocationPing {
	if x != nil {
		return x.Pings
	}
	return nil
}

type IngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProcessedCount int64                  `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_geo_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetProcessedCount() int64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *IngestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_geo_ingest_proto protoreflect.FileDescriptor

const file_proto_geo_ingest_proto_rawDesc = "" +
	"\n" +
	"\x16proto/geo_ingest.proto\x12\fgeoengine.v1\"\xec\x01\n" +
	"\fLocationPing\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tis_mocked\x18\b \x01(\bR\bisMocked\"H\n" +
	"\x14LocationBatchRequest\x120\n" +
	"\x05pings\x18\x01 \x03(\v2\x1a.geoengine.v1.LocationPingR\x05pings\"x\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x03R\x0eprocessedCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xb9\x01\n" +
	"\x10GeoIngestService\x12N\n" +
	"\x12SendSingleLocation\x12\x1a.geoengine.v1.LocationPing\x1a\x1c.geoengine.v1.IngestResponse\x12U\n" +
	"\x11SendBatchLocation\x12\".geoengine.v1.LocationBatchRequest\x1a\x1c.geoengine.v1.IngestResponseB5Z3github.com/AlexG695/geo-engine-go/proto/geopb;geopbb\x06proto3"

var (
	file_proto_geo_ingest_proto_rawDescOnce sync.Once
	file_proto_geo_ingest_proto_rawDescData []byte
)

func file_proto_geo_ingest_proto_rawDescGZIP() []byte {
	file_proto_geo_ingest_proto_rawDescOnce.Do(func() {
		file_proto_geo_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geo_ingest_proto_rawDesc), len(file_proto_geo_ingest_proto_rawDesc)))
	})
	return file_proto_geo_ingest_proto_rawDescData
}

var file_proto_geo_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_geo_ingest_proto_goTypes = []any{
	(*LocationPing)(nil),         // 0: geoengine.v1.LocationPing
	(*LocationBatchRequest)(nil), // 1: geoengine.v1.LocationBatchRequest
	(*IngestResponse)(nil),       // 2: geoengine.v1.IngestResponse
}
var file_proto_geo_ingest_proto_depIdxs = []int32{
	0, // 0: geoengine.v1.LocationBatchRequest.pings:type_name -> geoengine.v1.LocationPing
	0, // 1: geoengine.v1.GeoIngestService.SendSingleLocation:input_type -> geoengine.v1.LocationPing
	1, // 2: geoengine.v1.GeoIngestService.SendBatchLocation:input_type -> geoengine.v1.LocationBatchRequest
	2, // 3: geoengine.v1.GeoIngestService.SendSingleLocation:output_type -> geoengine.v1.IngestResponse
	2, // 4: geoengine.v1.GeoIngestService.SendBatchLocation:output_type -> geoengine.v1.IngestResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_geo_ingest_proto_init() }
func file_proto_geo_ingest_proto_init() {
	if File_proto_geo_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geo_ingest_proto_rawDesc), len(file_proto_geo_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geo_ingest_proto_goTypes,
		DependencyIndexes: file_proto_geo_ingest_proto_depIdxs,
		MessageInfos:      file_proto_geo_ingest_proto_msgTypes,
	}.Build()
	File_proto_geo_ingest_proto = out.File
	file_proto_geo_ingest_proto_goTypes = nil
	file_proto_geo_ingest_proto_depIdxs = nil
}
